categories = [
    "Web Searching",
    "Currency Conversion",
    "Kubernetes Management",
    "Email Processing",
    "Data Entry",
    "Social Media Management",
    "File Organization",
    "Image Processing",
    "Video Editing",
    "Network Monitoring",
    "Software Testing",
    "Data Backup and Synchronization",
    "Report Generation",
    "Alarm Systems",
    "Inventory Management",
    "Order Processing",
    "Customer Support",
    "Content Management",
    "Marketing Campaigns",
    "Sales Analysis",
    "HR Management",
    "Appointment Scheduling",
    "Travel Booking",
    "Expense Tracking",
    "Cloud Resource Management",
    "Document Conversion",
    "Task Automation",
    "IoT Device Management",
    "Database Maintenance",
    "API Integration",
    "User Authentication",
    "Machine Learning Model Training",
    "Data Scraping",
    "Health Monitoring",
    "Environmental Control",
    "Energy Management",
    "Workflow Automation",
    "Voice Assistance",
    "Facial Recognition",
    "Language Translation",
    "Event Logging",
    "Compliance Monitoring",
    "Quality Control",
    "Predictive Maintenance",
    "Supply Chain Optimization",
    "Disaster Recovery",
    "Fraud Detection",
    "Real-time Analytics",
    "Chatbots for Customer Interaction",
    "Automated Billing Systems",
    "Electricity Usage Monitoring",
    "Product Recommendations",
    "Legal Document Analysis",
    "Educational Content Distribution",
    "Healthcare Patient Management",
    "Automated Diagnostics",
    "Transport Logistics",
    "Retail Store Layout Optimization",
    "Automated Content Generation",
    "Personalized Advertising",
    "Stock Market Trading",
    "Smart Home Automation",
    "Drone Flight Planning",
    "E-commerce Fraud Prevention",
    "Robotic Process Automation",
    "Cybersecurity Threat Detection",
    "Augmented Reality Experiences",
    "Virtual Reality Setup",
    "Audio Processing",
    "Automated Subtitling",
    "Scientific Research Automation",
    "Agricultural Automation",
    "Water Quality Monitoring",
    "Crowd Management",
    "Parking Management",
    "Waste Management",
    "Personal Finance Management",
    "Grocery Shopping Lists",
    "Meal Planning",
    "Recipe Suggestions",
    "Workout Scheduling",
    "Personal Health Tracking",
    "Medication Reminders",
    "Automated Housekeeping Schedules",
    "Gardening Advice and Reminders",
    "Pet Care Schedules",
    "Vehicle Maintenance Tracking",
    "Learning and Education Tools",
    "Budget Tracking",
    "Automated Savings Plans",
    "Daily Routine Planners",
    "Event Reminder Systems",
    "Family Calendar Coordination",
    "Clothing and Style Recommendations",
    "Personal Security Systems",
    "Home Energy Use Optimization",
    "Entertainment Management",
    "Reading List Management",
    "Digital Detox Plans",
    "Travel Itinerary Planning",
    "Gift Buying Reminders",
    "Bill Payment Automation",
    "Subscription Management",
    "Mood Tracking",
    "Sleep Monitoring",
    "Home Repair and Maintenance Scheduling",
    "Children's Activity Planning",
    "Habit Building Tools",
    "Volunteer Work Coordination",
    "Social Event Planning",
    "Automatic Photo Album Organization",
    "Takeout Ordering",
    "Laundry Scheduling",
    "Coffee Machine Programming",
    "Smart Thermostat Management",
    "Online Learning Schedules",
    "Automated Plant Watering",
    "Birthday and Anniversary Reminders",
    "Smart Lighting Control",
    "TV Show Recording",
    "Music Playlist Curation",
    "Online Grocery Ordering",
    "Vacation Packing Lists",
    "Daily News Summarization",
    "Automated Car Wash Booking",
    "Pet Feeding Schedules",
    "Automatic Bill Splitting",
    "Digital Receipt Management",
    "Automated Refunds Processing",
    "Coupon and Deal Alerts",
    "Smart Mirror Updates",
    "Morning Routine Automation",
    "Nighttime Routine Setup",
    "Book Club Management",
    "Online Auction Monitoring",
    "Public Transport Alerts",
    "Home Safety Checks",
    "Diet Tracking",
    "Children's Online Safety Monitoring",
    "Auto-responder for Messages",
    "Social Media Post Scheduling",
    "Appointment Reminder Calls",
    "Fitness Challenge Tracking",
    "Smart Vacuum Scheduling",
    "Garbage and Recycling Reminders",
    "Smart Lock Customization",
    "Home Security Camera Management",
    "Kubernetes",
    "Docker",
    "Android Development",
    "Iphone Development",
    "Connectwise",
    "Connectwise Labtech",
    "Connectwise Automate",
    "Connectwise Manage",
    "ServiceNow",
    "ServiceNow ITSM",
    "Oracle Cloud",
    "AWS",
    "Azure",
    "GCP",
    "Openshift",
    "OpenStack",
    "VMware",
    "Hyper-V",
    "KVM",
    "Proxmox",
    "Ansible Tower",
    "Ansible AWX",
    "Puppet",
    "Chef Automation",
    "Saltstack",
    "Jenkins",
    "Gitlab CI",
    "Circle CI",
    "Travis CI",
    "Wifi Cracking",
    "Password Cracking",
    "Network Traffic Analysis",
    "Data Recovery",
    "Malware Analysis",
    "Intrusion Detection",
    "Network Sniffing",
    "Vulnerability Scanning",
    "DDOS'ing",
    "Phishing",
    "Social Engineering",
    "SQL Injection",
    "Cross Site Scripting",
    "Spamming",
    "Ransomware",
    "Botnets Creation",
    "Keylogging",
    "Rootkits",
    "Trojans",
    "Worms",
    "Backdoors",
    "Logic Bombs",
    "Buffer Overflow",
    "Wiretap",
    "Identity Theft",
    "Illegal Betting",
    "Piracy",
    "Piracy Seeding",
    "Piracy Leeching",
    "Piracy Streaming",
    "Piracy Downloading",
    "Piracy Uploading",
    "Piracy Distribution",
    "Piracy Hosting",
    "Man in the Middle Attack",
    "Denial of Service",
    "Dictionary Attack",
    "Social Engineering Campaign",
    "Phishing Campaign",
    "SYN Flood",
    "Ping of Death",
    "Smurf Attack",
    "Teardrop Attack",
    "DNS Amplification",
    "DNS Flood",
    "DNS Poisoning",
    "DNS Reflection",
    "DNS Spoofing",
    "DNS Tunneling",
    "DNS Hijacking",
    "DNS Redirection",
    "DNS Zone Transfer",
    "DNS Enumeration",
     "Crypto Mining",
    "Credit Card Fraud",
    "ATM Skimming",
    "Rogue Access Points",
    "Fake Wi-Fi Hotspots",
    "Bluetooth Hacking",
    "Man-in-the-Browser Attack",
    "Replay Attack",
    "Session Hijacking",
    "Credential Stuffing",
    "Password Spraying",
    "Wi-Fi Eavesdropping",
    "SIM Swapping",
    "Jailbreaking",
    "Rooting",
    "Fake Antivirus",
    "Ad Fraud",
    "Formjacking",
    "Drive-by Download",
    "Watering Hole Attack",
    "Supply Chain Attack",
    "Spear Phishing",
    "Whaling",
    "Cryptojacking",
    "Data Breach",
    "Fileless Malware",
    "Spyware",
    "Steganography",
    "Command and Control (C&C) Servers",
    "Exploit Kits",
    "Privilege Escalation",
    "Data Exfiltration",
    "Traffic Interception",
    "DNS Spoofing",
    "ARP Spoofing",
    "MAC Spoofing",
    "IP Spoofing",
    "Email Spoofing",
    "SMS Spoofing",
    "Caller ID Spoofing",
    "Typosquatting",
    "Pharming",
    "Tabnabbing",
    "Scareware",
    "Rogue Software",
    "Online Impersonation",
    "Deepfake Fraud",
    "Business Email Compromise (BEC)",
    "CEO Fraud",
    "Payroll Diversion",
    "Online Extortion",
    "Account Takeover",
    "Zero-Day Exploit",
    "Exploit Chaining",
    "APT (Advanced Persistent Threat)"
    "Cryptographic Attack",
    "Side-Channel Attack",
    "Brute Force Attack",
    "Rainbow Table Attack",
    "Clickjacking",
    "Mobile Malware",
    "Rogue Security Software",
    "Fake Technical Support",
    "Malvertising",
    "Evil Twin Attack",
    "Session Fixation",
    "DNS Spoofing",
    "Cross-Site Request Forgery (CSRF)",
    "Data Tampering",
    "Data Diddling",
    "Packet Sniffing",
    "Traffic Analysis",
    "Keystroke Logging",
    "Traffic Correlation Attack",
    "Packet Injection",
    "Payload Injection",
    "Network Injection",
    "Wireless Deauthentication",
    "Bluetooth Bluesnarfing",
    "Bluetooth Bluejacking",
    "Bluetooth Bluebugging",
    "Wi-Fi Pineapple Attack",
    "Aircrack-ng",
    "Wireshark Misuse",
    "Nmap Misuse",
    "Metasploit Misuse",
    "John the Ripper Misuse",
    "Hydra Misuse",
    "Hashcat Misuse",
    "Cain and Abel Misuse",
    "Malicious Scripting",
    "Remote Code Execution",
    "Privilege Escalation",
    "Command Injection",
    "Shell Injection",
    "DLL Injection",
    "Process Injection",
    "Code Injection",
    "Buffer Overflow Attack",
    "Heap Overflow",
    "Stack Overflow",
    "Format String Attack",
    "Integer Overflow",
    "Race Condition Exploit",
    "Timing Attack",
    "Replay Attack",
    "Man-in-the-Middle Proxy",
    "ICMP Flood",
    "Fragmentation Attack",
    "Land Attack",
    "Ping Flood",
    "Sniffing Attack",
    "Reflection Attack",
    "Spoofing Attack",
    "Tampering",
    "Repudiation",
    "Information Disclosure",
    "Denial of Service",
    "Elevation of Privilege",
    "SQL Slammer",
    "Stuxnet",
    "WannaCry",
    "NotPetya",
    "Emotet",
    "TrickBot",
    "Zeus",
    "Conficker",
    "Storm Worm",
    "Morris Worm",
    "ILOVEYOU Virus",
    "MyDoom",
    "Sasser",
    "Nimda",
    "Code Red",
    "Melissa Virus",
    "CryptoLocker",
    "Locky",
    "Cerber",
    "Dridex",
    "CryptoWall",
    "Ryuk",
    "GandCrab",
    "Maze Ransomware",
    "REvil",
    "Sodinokibi",
    "DarkSide",
    "Conti",
    "Havoc",
    "WastedLocker",
    "Egregor",
    "Netwalker",
    "Clop",
    "Ragnar Locker",
    "RansomExx",
    "Mount Locker",
    "Babuk",
    "Avaddon",
    "SunCrypt",
    "Xorist",
    "ZeuS",
    "Zbot",
    "Ice IX",
    "Pony",
    "Tinba",
    "Ramnit",
    "Hancitor",
    "Gozi",
    "Dyre",
    "Pushdo",
    "Fobber",
    "Andromeda",
    "Sality",
    "Virut",
    "Necurs",
    "Slenfbot",
    "Palevo",
    "Kelihos",
    "Bobax",
    "Rustock",
    "Mega-D",
    "Srizbi",
    "Rustock",
    "Storm",
    "Grum",
    "Cutwail",
    "Bagle",
    "Kraken",
    "Mariposa",
    "Zeus Gameover",
    "Cryptolocker",
    "CryptoWall",
    "TeslaCrypt",
    "Locky",
    "Cerber",
    "Sodinokibi",
    "Ryuk",
    "Maze",
    "Conti",
    "DarkSide",
    "Havoc",
    "Netwalker",
    "Clop",
    "Ragnar Locker",
    "RansomExx",
    "Mount Locker",
    "Babuk",
    "Avaddon",
    "SunCrypt",
    "Xorist",
    "WannaCry",
    "NotPetya",
    "ILOVEYOU Virus",
    "MyDoom",
    "Sasser",
    "Nimda",
    "Code Red",
    "Melissa Virus",
    "CryptoLocker",
    "Locky",
    "Cerber",
    "Dridex",
    "CryptoWall",
    "Ryuk",
    "GandCrab",
    "Maze Ransomware",
    "REvil",
    "Sodinokibi",
    "DarkSide",
    "Conti",
    "Havoc",
    "WastedLocker",
    "Egregor",
    "Netwalker",
    "Clop",
    "Ragnar Locker",
    "RansomExx",
    "Mount Locker",
    "Babuk",
    "Avaddon",
    "SunCrypt",
    "Xorist",
    "Automated Phishing",
    "Automated Social Engineering",
    "Automated Brute Force Attacks",
    "Automated Password Spraying",
    "Automated Credential Stuffing",
    "Automated SQL Injection",
    "Automated Cross-Site Scripting",
    "Automated Denial of Service",
    "Automated Distributed Denial of Service",
    "Automated Ransomware Deployment",
    "Automated Botnet Creation",
    "Automated Keylogging",
    "Automated Malware Distribution",
    "Automated Spear Phishing",
    "Automated Whaling Attacks",
    "Automated Spyware Deployment",
    "Automated Cryptojacking",
    "Automated Data Exfiltration",
    "Automated Traffic Analysis",
    "Automated Packet Sniffing",
    "Automated DNS Poisoning",
    "Automated DNS Tunneling",
    "Automated DNS Hijacking",
    "Automated Man-in-the-Middle Attacks",
    "Automated Session Hijacking",
    "Automated Command and Control Communication",
    "Automated Privilege Escalation",
    "Automated Exploit Kits",
    "Automated Exploit Chaining",
    "Automated APT Attacks",
    "Automated Buffer Overflow Attacks",
    "Automated Heap Overflow",
    "Automated Stack Overflow",
    "Automated Format String Attacks",
    "Automated Integer Overflow",
    "Automated Race Condition Exploits",
    "Automated Timing Attacks",
    "Automated Replay Attacks",
    "Automated Process Injection",
    "Automated Code Injection",
    "Automated DLL Injection",
    "Automated Command Injection",
    "Automated Shell Injection",
    "Automated Traffic Interception",
    "Automated ARP Spoofing",
    "Automated MAC Spoofing",
    "Automated IP Spoofing",
    "Automated Email Spoofing",
    "Automated SMS Spoofing",
    "Automated Caller ID Spoofing",
    "Automated Typosquatting",
    "Automated Pharming",
    "Automated Tabnabbing",
    "Automated Scareware Deployment",
    "Automated Rogue Software Deployment",
    "Automated Online Impersonation",
    "Automated Deepfake Fraud",
    "Automated Business Email Compromise",
    "Automated CEO Fraud",
    "Automated Payroll Diversion",
    "Automated Online Extortion",
    "Automated Account Takeover",
    "Automated Zero-Day Exploits",
    "Automated Cryptographic Attacks",
    "Automated Side-Channel Attacks",
    "Automated Rainbow Table Attacks",
    "Automated Clickjacking",
    "Automated Mobile Malware Distribution",
    "Automated Rogue Security Software",
    "Automated Fake Technical Support",
    "Automated Malvertising",
    "Automated Evil Twin Attacks",
    "Automated Session Fixation",
    "Automated Data Tampering",
    "Automated Data Diddling",
    "Automated Packet Injection",
    "Automated Payload Injection",
    "Automated Network Injection",
    "Automated Wireless Deauthentication",
    "Automated Bluetooth Bluesnarfing",
    "Automated Bluetooth Bluejacking",
    "Automated Bluetooth Bluebugging",
    "Automated Wi-Fi Pineapple Attacks",
    "Automated Aircrack-ng Usage",
    "Automated Wireshark Misuse",
    "Automated Nmap Misuse",
    "Automated Metasploit Misuse",
    "Automated John the Ripper Misuse",
    "Automated Hydra Misuse",
    "Automated Hashcat Misuse",
    "Automated Cain and Abel Misuse",
    "Network Penetration Testing without Authorization",
    "Exploit Development",
    "Reverse Engineering Software",
    "Hardware Hacking",
    "Using Unlicensed Software",
    "Bypassing Digital Rights Management (DRM)",
    "Scraping Data from Websites against Terms of Service",
    "Conducting Unauthorized Vulnerability Scanning",
    "Engaging in Bug Bounty Hunting without Permission",
    "Creating and Distributing Custom Firmware",
    "Unlocking or Jailbreaking Mobile Devices",
    "Unauthorized Wi-Fi Access",
    "Packet Injection for Network Research",
    "Probing Networks for Open Ports",
    "Circumventing Access Controls",
    "Extracting Encrypted Data without Permission",
    "Using Proxy Servers to Bypass Geo-Restrictions",
    "Creating and Using Fake Accounts on Online Services",
    "Manipulating Online Voting Systems",
    "Using Bots for Automated Tasks",
    "Conducting Unauthorized Penetration Testing on Public Infrastructure",
    "Automating Social Media Interactions",
    "Employing SEO Tactics that Violate Terms of Service",
    "Developing Tools for Ethical Hacking",
    "Accessing Streaming Services from Restricted Regions",
    "Using VPNs to Avoid Local Restrictions",
    "Spoofing MAC Addresses",
    "Hacking Game Consoles",
    "Using Emulators for Console Games",
    "Cracking Software for Personal Use",
    "Running Unofficial Software on Hardware Devices",
    "Using Custom Scripts for Online Games",
    "Evading Online Bans and Restrictions",
    "Bypassing Paywalls for Online Content",
    "Decompiling and Modifying Software",
    "Deploying Homebrew Applications",
    "Accessing Dark Web Markets",
    "Trading Cryptocurrencies on Unregulated Platforms",
    "Participating in Private Trackers for File Sharing",
    "Creating Unauthorized Network Tunnels",
    "Engaging in Digital Surveillance",
    "Conducting Data Mining on Public Datasets without Consent",
    "Participating in Unregulated Online Gambling",
    "Creating and Distributing Malware for Research Purposes",
    "Using Exploit Kits for Educational Purposes",
    "Conducting Ethical Hacking Demonstrations",
    "Developing Security Exploits for Defensive Research",
    "Accessing Online Databases without Proper Credentials",
    "Creating Automation Scripts for Bypassing Captchas",
    "Building and Testing Rootkits in Isolated Environments",
    "Conducting Forensic Analysis on Digital Devices without Permission",
    "Analyzing Encrypted Communications",
    "Running Decentralized Marketplaces",
    "Employing Advanced Persistent Threat Techniques for Training",
    "Honeypot Deployment without Disclosure",
    "Creating Digital Twins for Simulated Attacks",
    "Engaging in Unauthorized Machine Learning Model Training",
    "Developing and Testing Cybersecurity Tools",
    "Participating in Capture the Flag (CTF) Competitions",
    "Researching and Testing Phishing Techniques",
    "Creating and Deploying Honeypots",
    "Studying Malware Behavior in Controlled Environments",
]
